authors:
  shannah:
    name: Shannah
    description: Researcher @ SIEMENS | Machine Learning @ TUM/LMU | ex-BMW
    avatar: https://avatars.githubusercontent.com/u/16389789?v=4
    url: https://sh2282000.github.io
